EXPOSERS: Initialize EFxceptionsContext
The-Standard-Organization/STX.EFxceptions.Cosmos pull request #8
Opened 2024-01-27 10:34 UTC by ZafarUrakov

Closes #3 
@cjdutoit

2024-01-27 11:02 UTC, ZafarUrakov commented
This is without tests

2024-01-29 09:26 UTC, ElbekDeveloper requested changes

2024-01-29 09:26 UTC, ElbekDeveloper commented on STX.EFxceptions.Cosmos/EFxceptionsContext.cs
> +                new CosmosEFxceptionService(errorBroker);
Make it scoped `{ }`

2024-01-29 16:16 UTC, cjdutoit commented on STX.EFxceptions.Cosmos/EFxceptionsContext.cs
> +    {
where is your constructors?

2024-01-29 16:53 UTC, cjdutoit approved these changes

2024-01-29 16:53 UTC, merged